# .scrutinizer.yml

checks:
  php:
    code_rating: true
    duplication: true
build:
  environment:
    mongodb: true
    php: '7.1'
  dependencies:
    before:
      - 'pecl install mongodb'
filter:
  excluded_paths:
    - "tests/"